### ISSUE TITLE
Failed to load resource on toast.js

### ISSUE THREAD

**Issue by cagdassalur** [Samsung/cordova-plugin-toast#11]
When i try to debug my app using browser i get the error `Failed to load resource: the server responded with a status of 404`

I followed every instruction on the github page when setting up the enviroment but i still get this.

**Comment by sukyunglee** [comment]
cagdassalur,
Hello.
This is Sue. First, thank you for your concern.

I think that it maybe security issue of Chrome browser.
Chrome browser basically protects to access cross domain.
you can simply configure Chrome browser option to avoid.

Please run Chrome browser with below option.
chrome.exe --allow-access-from-files --disable-web-security

Thanks.
Sue

**Comment by cagdassalur** [comment]
Thanks for your reply. Will I be able to make cross domain requests on Tizen and Smart Tv's after I deploy?

**Comment by sukyunglee** [comment]
cagdassalur,

You don't have to configure on Tizen and Smart TV.
There are no problems.
It is needed only on Chrome browser.

Thanks.
Sue

**Comment by cagdassalur** [comment]
Thanks!

**Comment by cagdassalur** [comment]
Sorry for reopening but where is the chrome that cordova runs and how can i run it with arguments? Im on osx and i use the command `cordova emulate browser`

**Comment by sukyunglee** [comment]
cagdassalur,
I'm sorry, I thought your PC OS is Windows.

I think the below URL helps your problem.
http://superuser.com/questions/271678/how-do-i-pass-command-line-arguments-to-dock-items

Thanks.
Sue

**Comment by cagdassalur** [comment]
Thanks for the reply. I though cordova was using a different build of chromium for testing. Isn't that the case?

**Comment by cagdassalur** [comment]
By the way i tried the app on samsung smart tv emulator via virtualbox just now and i get this error:
`0138 ReferenceError: Can't find variable: toast`
What could be the problem?

**Comment by pwsses** [comment]
plz refer issues #9 
https://github.com/Samsung/cordova-plugin-toast/issues/9

I think it is emulator env issue.

**Comment by cagdassalur** [comment]
i have the tag and everything. I set up the enviroment exactly like shown in the wiki. Still i get the error on both samsung tv emulator and browser.

**Comment by cagdassalur** [comment]
For future reference putting the built app into Apps shared directory of the emulator and running it doesn't work. You need to import the app into samsung sdk eclipse and run from there.

**Comment by epogash** [comment]
I am also receiving a 404 error on toast.js within the web browser after following all of the instructions and running the sample app using the command line options:
chrome.exe --allow-access-from-files --disable-web-security

**Comment by HelaGone** [comment]
@cagdassalur I'n new on Samsung development and I have the same issue on Tizen platform. But in Orsay, I don't know exactly what are the paths for Apps and Tools that I need to configure on virtualbox So, I've been unable to test my TOAST app on Orsay emulator. Can you give me a brief explanation please?
