### ISSUE TITLE
toast.MediaPluginPlayReady is not a constructor error on sample app DrmMedia

### ISSUE THREAD

**Issue by cagdassalur** [Samsung/cordova-plugin-toast#12]
It gives the error on line 48 of media.js. App was created from template using instructions on wiki.

**Comment by sukyunglee** [comment]
cagdassalur,
Hello.
This is Sue. First, thank you for your concern.

I think you test DrmMedia sample app on Chrome browser, right?
DRM play is not supported on Chrome browser,
It is supported only on Tizen and Smart TV.

Please check it.

Thanks.
Sue

**Comment by cagdassalur** [comment]
I was using Chrome Browser. Thanks!
