### ISSUE TITLE
Cannot stream video with media plugin

### ISSUE THREAD

**Issue by cagdassalur** [Samsung/cordova-plugin-toast#13]
When i give a *.ts or *.m3u8 file as a source to media.open() i get the following error on my browser:

```
undefined:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.
media.js:107 MediaError is occured: {"type":"ERROR","data":{}}
```

**Comment by sukyunglee** [comment]
cagdassalur,
Hello.
This is Sue. First, thank you for your concern.

Unfortunatly, some media formats(*.ts, *.m3u8, etc.) are not supported On Chrome browser.
On chrome browser, TOAST uses Video tag.
So formats to be supported on Video tag are supported.

Please check it.

Thanks.
Sue

**Comment by AlinaDovbysheva** [comment]
Hello.

Please, could you tell how to test application with an HLS(m3u8) stream?

Thanks.
Alina
