### ISSUE TITLE
Media is a singleton?

### ISSUE THREAD

**Issue by BryanCrotaz** [Samsung/cordova-plugin-toast#15]
If Media is a singleton then how do we play more than one video at once? (e.g. two SD videos on an HD capable decoder)

I would wish to preload the next video while the current one is playing.

**Comment by pwsses** [comment]
currently, The Media's instance can be created with getInstance method which creates singleton instance. so toast.media does not support preload(prebuffering)
But I have plan to support it. in the end of year.
thanks for your interest.
https://github.com/Samsung/cordova-plugin-toast/blob/master/docs/toast.Media.md

**Comment by BryanCrotaz** [comment]
What is the recommended best practice workaround to achieve seamless back to back video playback today without this feature?

**Comment by hvintro** [comment]
Hi!, It is not possible play two videos at the same page right? Well, in my case an audio and a video running at the same time. 

Cheers.
