### ISSUE TITLE
Media Playback causes errors

### ISSUE THREAD

**Issue by detesto** [Samsung/cordova-plugin-toast#16]
On one app, I create an instance of the player to play audio files (songs). On certain occasions, on both platforms the app will fail to play the files.

On orsay I only get the error MediaError occured: {"type":"ERROR","data":"0"}

On tizen, it specifies MediaError occured: {"type":"ERROR","data":"PLAYER_ERROR_NOT_SUPPORTED_FILE"}

The thing is, that if I retry with the file it sometimes does play it without issues.

Is this an error on toast or is this a platform error? I doubt it could be a platform error seeing it occur on both.

**Comment by pwsses** [comment]
Hi. 

Thanks for your issue report.

Can you share audio content url or file ?? 

I will check the reason of issue with your audio content.

thanks.
