### ISSUE TITLE
its works on ORSAY?

### ISSUE THREAD

**Issue by salexch** [Samsung/cordova-plugin-toast#17]
Hi,
I build the app with TOAST and it works great on tizen (has to add manualy cordova_plugins.js and plugins folder), but on orsay it refuses to load.
device ready event is never fired.
also when I compile the project it doesn't add plugins folder and cordova_plugins.js is missing.
also I need manualy to copy toast.js to the project (I'm on windows)

for example, in cordova-orsay.js on line 1389 there is a window.onShow = function (..
which is never been called (it very hard to debug on orsay..)

maybe somebody can upload working example with all files needed (that I wont need to biuld orsay corodva and toast localy)?

**Comment by darangkim** [comment]
Hello,
Thank you for your report.

I checked TOAST of latest version on 14' device(Orsay), there are no any problems.
Please send me your detailed test environment. (Firmware version of your device ,TOAST version and so on,,)

I share the 'TestRunner' project for Orsay. [(TestRunner0607_Orsay.zip)](https://github.com/Samsung/cordova-plugin-toast/files/302079/TestRunner0607_Orsay.zip)

You can build the test project following the below guide using [cordova-test-runner](https://github.com/Samsung/cordova-plugin-toast/tree/master/cordova-test-runner)
- [Prepare to start](https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-to-start)
- [Create Project](https://github.com/Samsung/cordova-plugin-toast/wiki/Create-Project)
- [Prepare and Build](https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-and-Build)

Thank you.

**Comment by salexch** [comment]
Please tell me. When I do: "grunt prepare-sectv:sectv-orsay"
Should it create "plugins" folder and "cordova-plugins.js" file in my
project folder?

**Comment by salexch** [comment]
1. running the project (TestRunner0607_Orsay.zip) as is in the emulator doesnt work, 
it says that  Failed to load resource: fail to read a resource form decryptied file file:///home/smarttv/Apps/testToast/cordova_plugins.js
2. then I created new project via Create Project and copied files from TestRunner0607_Orsay.zip there,
after running grunt sectv-prepare:sectv-orsay it created platforms\sectv-orsay\www with project files.
BUT I don't see  "cordova_plugins.js" and no "plugins" folder in the prepared project!

environment: emulaor 5_1
toast: 1.0 (does't work for latest version too)

If I copy the missing files manually it doesn't work because device ready is not fired after 5 sec.. 


I have to use emulator cause I didnt find a way to debug on tv

**Comment by darangkim** [comment]
The orsay/tizen don't need the 'plugins' folder and 'cordova-plugins.js' file.
They are in browser only. There is a toast.js instead of them for orsay/tizen.

You can create your project as the below.

```sh
    # Create cordova project
    $ cordova create tmplApp --src=cordova-plugin-toast/sample/media
    $ cd tmplApp

    # Beware of hidden file
    $ cp -rf ../grunt-cordova-sectv/sample/. ./
    $ npm install ../grunt-cordova-sectv
    # Grunt task for build and package

    # Install dependency modules
    $ npm install

    # For toast browser simulator
    $ cordova platform add browser

    # Mandatory plugins for using browser simulator (not for other platforms)
    $ cordova plugin add cordova-plugin-device
    $ cordova plugin add cordova-plugin-network-information
    $ cordova plugin add cordova-plugin-globalization

    # Add toast plugin
    $ cordova plugin add ../cordova-plugin-toast
```

You can only check the browser folder in 'platforms' folder.
You should do the following steps in your project for making the orsay.

```sh
    # prepare for sectv-orsay
    $ grunt sectv-prepare:sectv-orsay

    # build and package for sectv-orsay
    $ grunt sectv-build:sectv-orsay
```

You can check running the orsay app without copying the "plugin" folder and 'cordova-plugins.js' file.

And 
Running the "TestRunner0607_Orsay.zip" project is working fine on emulator(emulator 5_1).
If you share your test project, I will check it on my emulator.

Thank you.

**Comment by salexch** [comment]
on wundows
I'm using this to follow the TOAST steps (it assumes that npm, cordova and grunt are installed)
[windows_setup.zip](https://github.com/Samsung/cordova-plugin-toast/files/303160/windows_setup.zip)
to create a project I use step5 like this: 
C:\TOAST\5_create_project.cmd {PROJECT_NAME}
1. add toast.js to the index.html
2. run: grunt sectv-prepare:sectv-orsay
3. create new test project in samsung ide
4. run on emulator

result: 
![toast](https://cloud.githubusercontent.com/assets/1044084/15868329/1a7807e8-2cf0-11e6-9d5c-bcbfaef143ea.jpg)


project:
[toasttest.zip](https://github.com/Samsung/cordova-plugin-toast/files/303204/toasttest.zip)

**Comment by darangkim** [comment]
I'm checking your problem.
I can't find any problem in your files till now.

Though you are inconvenient, 
you can make the normal project using my guide without .cmd files.
Please use this way before solving your issue.

I will contact you shortly with solution.

Thank you.

**Comment by darangkim** [comment]
I fixed a small error in the "4_compile.cmd".
And we add some error message for checking this issue.

Please check attachments. ([orsay.zip](https://github.com/Samsung/cordova-plugin-toast/files/322603/orsay.zip) / [cmd_files.zip](https://github.com/Samsung/cordova-plugin-toast/files/322604/cmd_files.zip))
I'm using this cmd files to make the orsay app.
This app is working fine. (You can check the 'deviceready' event)

Thank you.

**Comment by salexch** [comment]
Hi,
thank you. 
sorry to say this but orsay.zip doesn't work.
I imported the project to IDE Version : 5.1 

and run on emulator 2014_Smart_TV_Emulator_5_1

LOG
0001  [INFO] window.onShow

0002  [INFO] window.onFocusin

0003  [INFO] window.onShow

0004  [INFO] window.onFocusin

0005  cordova/platform: orsay bootstrap BEGIN

0006  	return Network

0007  adding proxy for NetworkStatus

0008  adding proxy for Console

0009  adding proxy for Device

0010  adding proxy for Globalization

0011  cordova/platform: orsay bootstrap END

0012  adding proxy for toast.inputdevice

0013  	return Window

0014  adding proxy for toast.tvwindow

0015  	return Window

0016  adding proxy for toast.tvchannel

0017  adding proxy for toast.tvaudiocontrol

0018  adding proxy for toast.drminfo

0019  adding proxy for toast.application

0020  adding proxy for toast.Media

0021  [webapis.js] loading start

0022  	[webapis.js] Version : 1.2.14

0023  Print: AllShare Web API  JS: 1.3.0.9

0024  [webapis.js] loading finished

0025  [webapis] onHide function added.

0026  [webapis] onShow function added.

0027  deviceready has not fired after 5 seconds.

0028  Channel not fired: onNativeReady

0029  Channel not fired: onCordovaReady


I will try the fixed cmd files later, 
Thank you again.

**Comment by darangkim** [comment]
It is working fine on my emulator.(2014_Smart_TV_Emulator_5_1)

...

0265  connection network type is Ethernet

0266  webapis._plugin.getSEFAvailable()

0267  2012's Webkit platform

0268  [webapis] _plugin(NNavi,GetModelCode)

0269  getPluginName(NNavi)

0270  	return NNavi

0271  addPluginObject(NNavi,true)

0272  Create SEF Plugin for NNavi: <OBJECT id="_plugin_NNavi" classid="clsid:SAMSUNG-INFOLINK-SEF" style="display:block;position:absolute;width:0px;height:0px;"></OBJECT>

0273  SEF Open Returns 1

0274  SEF Open Succeded!!!

0275  	returns LNXXB650_KOR

0276  webapis._plugin.getSEFAvailable()

0277  2012's Webkit platform

0278  [webapis] _plugin(NNavi,GetFirmware)

0279  getPluginName(NNavi)

0280  	return NNavi

0281  	returns T-INFOLINK2014-1000

0282  webapis._plugin.getSEFAvailable()

0283  2012's Webkit platform

0284  [webapis] _plugin(Network,GetMAC,1)

0285  getPluginName(Network)

0286  	return Network

0287  	returns 0800279b3e8c

0288  sMacAddr == 0800279b3e8c

0289  webapis._plugin.getSEFAvailable()

0290  2012's Webkit platform

0291  [webapis] _plugin(NNavi,GetDUID,0800279b3e8c)

0292  getPluginName(NNavi)

0293  	return NNavi

0294  	returns BDCAAKYFDB4FQ

0295  [cordova-plugin-console][LOG] adding proxy for toast.inputdevice

0296  [cordova-plugin-console][LOG] 	return Window

0297  [cordova-plugin-console][LOG] adding proxy for toast.tvwindow

0298  [cordova-plugin-console][LOG] 	return Window

0299  [cordova-plugin-console][LOG] adding proxy for toast.tvchannel

0300  [cordova-plugin-console][LOG] adding proxy for toast.tvaudiocontrol

0301  [cordova-plugin-console][LOG] adding proxy for toast.drminfo

0302  [cordova-plugin-console][LOG] adding proxy for toast.application

0303  [cordova-plugin-console][LOG] adding proxy for toast.Media

0304  [cordova-plugin-console][LOG] 	return AppCommon

0305  [cordova-plugin-console][LOG] 	return NNavi

0306  [cordova-plugin-console][LOG] connection network type is Ethernet

0307  Received Event: deviceready

0308  [cordova-plugin-console][LOG] Received Event: deviceready

Please check fixed cmd files and wiki.
I hope you to be successful.

Thank you.
