### ISSUE TITLE
Use this plugin to control smart-tv from local machine

### ISSUE THREAD

**Issue by mmende** [Samsung/cordova-plugin-toast#18]
Hi,

I created a plugin for [Homebridge](https://github.com/nfarina/homebridge) that allows me to control the volume, channel and on/off state of my samsung tv running Orsay over siri. The plugin currently uses the old [unofficial network protocol](https://wiki.samygo.tv/index.php5/Samsung_TV_network_remote_control_protocol) that seems not to exist on the newer Tizen tv's anymore. Therefore I would like to exchange this component with a solution that fits both, the old Orsay based smart tv's and the newer Tizen based samsung tv's. My concrete question is now if this plugin is just for developing smart tv apps or if it would also be possible to divert the plugins intended use to control smart tv's in the same network from another machine.

Thanks in advance.

**Comment by prozanne** [comment]
Hi!
Unfortunately, we recommend not to use unofficial network protocol.
But I hope your great project is going well.
Thanks.
