### ISSUE TITLE
Better setup script suggestion

### ISSUE THREAD

**Issue by tbazelczuk** [Samsung/cordova-plugin-toast#2]
I just want to suggest to improve project setup process because there are a lot of manual commands thats have to be done (below links). Could you consider create additional github repository for sample application that contains proper configuration prepared already?

https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-to-start
https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-and-Build

**Comment by prozanne** [comment]
You mean, shell file which contains whole process?

**Comment by pwsses** [comment]
or make new grunt application which is similar grunt-cordova-sectv ?

**Comment by tbazelczuk** [comment]
Yes, it could be a grunt task to setup whole project together.

**Comment by prozanne** [comment]
That sounds great. It would surely help to developers who use TOAST project. We will consider about it(not soon). If we support and accept your suggestion someday, we hope to create it for grunt task in grunt-cordova-sectv.(not repository). We really appreciate you to your good suggestion and interesting.

**Comment by rikoopa** [comment]
Im for it too. Its a smart idea for automation and makes starters developing simplier.
