### ISSUE TITLE
No mouse cursor.

### ISSUE THREAD

**Issue by e1ad** [Samsung/cordova-plugin-toast#20]
Try to use video elemet and play a video.
But no mouse cursor. (Using sectv-orsay plugin on my Smart tv)
The video is playing well on using autoplay attr.

**Comment by pwsses** [comment]
Hi thanks for your report 
sectv-orsay platform need mouse tag in config.xml when use mouse device.
please check to config.xml file in your application
If it does not have mouse tag, add mouse tag as follows
<mouse>y</mouse>

**Comment by e1ad** [comment]
Child of which tag is it should be? Under the main widget tag?

**Comment by pwsses** [comment]
Yes 
Under the main widget tag in config.xml
thanks

**Comment by e1ad** [comment]
Thank a lot to you !

**Comment by e1ad** [comment]
It does not work..
Adding my congif.xml file.
Still no mouse pointer.

**Comment by pwsses** [comment]
Orsay TV needs only one thing to show the mouse pointer which is  mouse tag in config.xml file.
I don't have any idea about cause.
Can you share your App souce or config.xml file by our E-mail(toast@samsung.com) ?
And please let me know, your Smart TV env. (model name or years of TV ) 
If you bulid orsay App using grunt-cordova-sectv, mouse tag is default tag in config.xml

**Comment by e1ad** [comment]
Thanks, I will do so

**Comment by pwsses** [comment]
I checked your config.xml file.
It is cordova project config.xml file. please remove mouse tag in cordova project config.xml file
mouse tag is orsay tv spec so you will check orsay config,xml file in result of sectv-prepare folder 
(maybe folder path is platforms/sectv-orsay/www folder in your cordova project)
please check again config.xml file. 
I think, If you sure according to our guide(Prepare and Build (url : https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-and-Build)), 
it will already have a mouse tag.

**Comment by e1ad** [comment]
I talking about the remote controller mouse pad,right? No an extranl mouse

בתאריך 28 בספט׳ 2016 13:18,‏ "Woosik Park" <notifications@github.com> כתב:

I checked your config.xml file.
It is cordova project config.xml file. please remove mouse tag in cordova
project config.xml file
mouse tag is orsay tv spec so you will check orsay config,xml file in
result of sectv-prepare folder
(maybe folder path is platforms/sectv-orsay/www folder in your cordova
project)
please check again config.xml file.
I think, If you sure according to our guide(Prepare and Build (url :
https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-and-Build)),
it will already have a mouse tag.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Samsung/cordova-plugin-toast/issues/20#issuecomment-250128274>,
or mute the thread

**Comment by pwsses** [comment]
Remote controller mouse has same spec with extnal mouse.
If you completed the remote controller pairing to TV.
