### ISSUE TITLE
"Failed to install" error message.

### ISSUE THREAD

**Issue by e1ad** [Samsung/cordova-plugin-toast#21]
I tried to upload to my Samsung tv a Toast app that using AngulaJs and Jquery,
By just keep and get the same error message :  "Failed to install. For more information, visit http://www.samsungdforum.com/Support/TVAppsSecurity".

I tried and the following steps :

1 - Following step by step on the 'Toas't instructions in this GitHub project  and create Cordova project.
2 - Login using the developer user on my Samsung tv.
3 - Enter my computer ip.
4- Create 'widgetlist.xml' file , packing my project and successfully upload a 'hello world' app to my tv, using the sync app option.
5 - Create a new cordova project that using AngularJs  and Jquery framework, try and upload the new  app , using the sync app option , get an error saying :
 "Failed to install. For more information, visit http://www.samsungdforum.com/Support/TVAppsSecurity".

I am using Samsung UA46F6400.

Elad

**Comment by prozanne** [comment]
Hi

Are you using some other apis that is not supported in TOAST? If so what kind of apis are you using in your application?
There are many similar issue cases at SamsungDForum site.
Please refer belows.

https://www.samsungdforum.com/Search/UnifiedSearch?schoption=ALLCATEGORY&hdnSchText=TVAppsSecurity

**Comment by e1ad** [comment]
Its happened when I try to uploads a realy simpale app.One that only use
jquery and Angularjs.
No use of other api.

בתאריך 4 באוק׳ 2016 7:46,‏ "Hyojin Kim" <notifications@github.com> כתב:

**Comment by e1ad** [comment]
I see some people in your support from mention using a signature file.
Do I need one ?

בתאריך 4 באוק׳ 2016 8:03,‏ "Elad Noy" <noyelad@gmail.com> כתב:

**Comment by prozanne** [comment]
Hi
Unfortunately It seems not TOAST origin issue.
As you said, It might be required signature file.
I think you can receive help through SamsungDforum site more specifically.

And If you just want to launch your application, there is a way for using usb installation.
If you put your project folder at your usb root and put usb slot at the TV device, It is installed automatically.
