### ISSUE TITLE
node.js 

### ISSUE THREAD

**Issue by legend153** [Samsung/cordova-plugin-toast#22]
안녕하세요 node js 와 socket.io를 이용한 tizen tv app을 개발을 하고있는 개발자입니다.
simulator에서는 클라이언트(tizen tv)와 서버가 socket 통신이 문제없이 되지만,
emulator에서는 app 시작하자마자 종료가 되는 현상이 나타납니다.

현재 tizen sdk2.4를 사용하고 있는 중입니다. socket.io가 tizen에서 지원이 되는지 궁금합니다.
감사합니다.

**Comment by yongjuYoon** [comment]
안녕하세요 :) legend153님,

문의 하신 socket.io가 tizen에서 지원 가능한지에 대한 답변입니다.

Tizen은 표준 기반의 소프트웨어 플랫폼입니다. 따라서 socket.io를 지원하고 있습니다.

하지만 socket.io는 현재 TV에서 지원하고 있지만 emulator에서는 지원하지 않습니다.

추가 검토가 필요하시면 소스 공유 부탁드립니다.

이후 TOAST 문의사항이 아닌 Tizen 관련 내용은 https://www.samsungdforum.com에 문의 바랍니다.
