### ISSUE TITLE
Errors while setting process

### ISSUE THREAD

**Issue by pavelivanov** [Samsung/cordova-plugin-toast#23]
Hi there. I used **shell file** for preparing. In process of compiling I got errors:

> Fatal error: cordova.js, toast.js file are not exist.
================ Prepare for sectv-tizen platform
Running "sectv-prepare:sectv-tizen" (sectv-prepare) task

> Fatal error: cordova.js, toast.js file are not exist.
================ Prepare for tv-webos platform
Running "sectv-prepare:tv-webos" (sectv-prepare) task

And after it finished I noticed weird 'nnnt' in Gulpfile.js, package.json.. I think it's partials of \n\n\n\t in strings from shell file. I use Mac 10.11.6

**Comment by darangkim** [comment]
Hello,
Thank you for your reporing.

This error is by \n\n\n\t string on Mac as you mentioned before.
So I fixed this issue. Please check again.

Thank you.
