### ISSUE TITLE
verimatrix

### ISSUE THREAD

**Issue by salexch** [Samsung/cordova-plugin-toast#24]
Hi, 
Is verimatrix supported? I didn't find any reference in docs and not in the source code.
Thank you!

**Comment by darangkim** [comment]
Hello,

Unfortunately verimatrix is not supported.
Until now, We estimate that verimatrix is an infrequently used DRM on Smart TV.
If request to support the verimatrix increase, we will consider it.

Now, If you want to support verimatrix, you need to realize by platform with [this document](https://github.com/Samsung/cordova-plugin-toast/wiki/How-to-detect-platform).

Thank you.

**Comment by kevinbol** [comment]
can you support verimatrix drm on Tizen ?
