### ISSUE TITLE
TestRunner0607_Orsay.zip - Not Work Orsay 2014

### ISSUE THREAD

**Issue by Belsim77** [Samsung/cordova-plugin-toast#25]
Hi,

we triedto install the TestRunner0607_Orsay.zip and it failed on device:

Samsung Smart TV Orsay
Model UE55F7000
Software version : T-FXPDEUC-1118.0

We hope in your help
Thank you ad best regards

**Comment by yongjuYoon** [comment]
Hello, Belsim77,

It is difficult to check the exact reason with your question.

so plz give it to me, ".zip" file.

Thank you.
