### ISSUE TITLE
Supported Orsay Platforms. Which ones?

### ISSUE THREAD

**Issue by rikoopa** [Samsung/cordova-plugin-toast#3]
Hello,

in the Wiki somewhere i read supported Devices for Orsay and i only saw 2014 mentioned as also for the examples.
I have a 2012 Device Smart TV. Will this work with TOAST too or will we have some limitations or even no Support?

Greetings

**Comment by sukyunglee** [comment]
Unfortunately, TOAST supports Orsay platform, 2014 and 2013.
2012 Platform is not supported. Sorry not to be helpful.

And then,
We just recognize that supported platform information is wrong.
We will update and add the supported platforms list.

Thanks.

**Comment by rikoopa** [comment]
Hi,

2012 model is capable for HTML5, CSS3, JS and Flash. Why wouldn't it work?

When i read legacy smart TV that it must be all from 2011 to 2014. otherwise its not true on Samsungs website either

**Comment by sukyunglee** [comment]
I appreciate how you feel.
We apologize for not supporting 2012, 2011 platform.

TOAST plugin is designed for "product APIs".

Althouth 2012, 2011 model capable for HTML5, CSS and etc, (similar 2013, 2014)
these Product APIs are a little different from 2013, 2014 model.
So we determine not to support these platforms.

Please understand our policy, sorry not to be helpful one more.

**Comment by rikoopa** [comment]
Ok, i see.
When you say a "little different", you mean it is technically possible and there might be limitations?
If it was possible, i wish you would support these "older" devices. That would be great.

Thanks

**Comment by sukyunglee** [comment]
On 2012, 2011 model, it maybe technically possible, but there are some limitations.
However, if we determine to support 2012, 2011 model with imperfections, we inform the news.

Thank you for your time and consideration.
