### ISSUE TITLE
Tizen build error

### ISSUE THREAD

**Issue by bstegman** [Samsung/cordova-plugin-toast#32]
My app was building fine for Tizen and even submitted it to the app store but now I'm getting this error when I run "grunt sectv-build:sectv-tizen".

[4mRunning "sectv-build:sectv-tizen" (sectv-build) task[24m

Start packaging Samsung Tizen TV Platform......
Tizen CLI 1.3.5

Setting configuration is succeeded....

Build Web Application:   10% ( 1/10)
Build Web Application:   20% ( 2/10)
Build Web Application:   40% ( 4/10)
Build Web Application:   50% ( 5/10)
Build Web Application:   60% ( 6/10)
Build Web Application:   70% ( 7/10)
Build Web Application:   80% ( 8/10)
Build Web Application:  100% (10/10)
Build Web Application:  100% (10/10)

BUILD SUCCESSFUL

Output path:/samsung/laze-life/platforms/sectv-tizen/www/.buildResult
Excluded: [.build/*, .build, .sign/*, .sign, webUnitTest/*, webUnitTest, .externalToolBuilders/*, .externalToolBuilders, .buildResult/*, .buildResult, .settings/*, .settings, .package/*, .package, .tproject, .project, .sdk_delta.info, .rds_delta, *.wgt, .tizen-ui-builder-tool.xml]
Total time: 00:00:00.432
Author certficate: /tizen-studio-data/keystore/author/lazelife.p12
Distributor1 certificate : /tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-signer.p12
Excludes File Pattern: {.manifest.tmp, .delta.lst}
Ignore File: /samsung/laze-life/platforms/sectv-tizen/www/.buildResult/.manifest.tmp
Package File Location: /samsung/laze-life/platforms/sectv-tizen/www/.buildResult/LazeLife.wgt
[31mFatal error: Path must be a string. Received [ 'Package File Location: /samsung/laze-life/platforms/sectv-tizen/www/.buildResult/LazeLife.wgt',
  '/samsung/laze-life/platforms/sectv-tizen/www/.buildResult/LazeLife.wgt',
  index: 435,
  input: 'Author certficate: /tizen-studio-data/keystore/author/lazelife.p12\nDistributor1 certificate : /tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-signer.p12\nExcludes File Pattern: {.manifest.tmp, .delta.lst}\nIgnore File: /samsung/laze-life/platforms/sectv-tizen/www/.buildResult/.manifest.tmp\nPackage File Location: /samsung/laze-life/platforms/sectv-tizen/www/.buildResult/LazeLife.wgt\n' ][39m

**Comment by yongjuYoon** [comment]
@bstegman 
You can solve this problem(#32) now.
We fixed the code related this error that is not critical.

So plz update the "grunt-cordova-sectv" for using "git pull" now.
Related url : https://github.com/Samsung/grunt-cordova-sectv

And then if you build project, you will fine.

Thank you.
