### ISSUE TITLE
toast media player doesn't emit "ENDED" event

### ISSUE THREAD

**Issue by jamesmskelsey** [Samsung/cordova-plugin-toast#33]
Toast media player works fine in the browser emulator. Doesn't work in the TIZEN Studio version 1.1.0 (from 2016-12-21?!) emulator that comes with it. 

When I load a video in the toast browser emulator, the media player is properly updated with the duration of the file being loaded and then I can use that.

When I load a video in the tizen studio emulator, the media player is not updated with the duration (the duration is, however, for some reason, put in to the _currentPosition variable. Which then seems to result in the ended event not being emitted, so I can't even use the events properly.

**Comment by yongjuYoon** [comment]
Hello, jamesmskelsey

The result that I tested in the tizen studio emulator and browser was no problem.

So plz update the emulator with latest version.

Thank you.

**Comment by jamesmskelsey** [comment]
Well I feel dumb - I didn't realize that I could open the emulator outside of the studio and then open the .wgt file. I have been beating myself up for days... that...

helps a lot. Too bad nothing says that anywhere.

Thanks! I'll close the issue out.
