### ISSUE TITLE
Question about the wgt artifact generated. 

### ISSUE THREAD

**Issue by guipdutra** [Samsung/cordova-plugin-toast#36]
Hello, I did the prepare/build command for Tizen OS and a "HelloCordova.wgt" was generated. I'm not sure how to run this in the Tizen emulator, I tried a lot of things but I could not push the artifact.

Someone have some tip/link about the deploy in emulator?

**Comment by prozanne** [comment]
Hello,
You can run your application through Tizen Studio(Tizen SDK).
Please refer below guide for running emulator.

http://developer.samsung.com/tv/develop/getting-started/using-sdk/tv-emulator

**Comment by guipdutra** [comment]
Thank you.
