### ISSUE TITLE
Media application gives plugin not supported on Tizen simulator

### ISSUE THREAD

**Issue by richardman1** [Samsung/cordova-plugin-toast#40]
After following the guidelines to make a media application demo, it works on webOS.

On Tizen, the video plays,but I get a small rectangular in the left upper corner of the Tizen simulator saying plugin not supported.

![image](https://cloud.githubusercontent.com/assets/8642626/23709769/ce5f523c-041a-11e7-8d93-9d42adeaa1c6.png)

**Comment by yongjuYoon** [comment]
Hi, @richardman1 

The several apis aren't supported in simulator.

So we recommend emulator than simulator for test app.

Thank you.

**Comment by richardman1** [comment]
That is true indeed,  I completely forgot about this detail. I hope you can fix my problem that I can't install applications on my emulator.
