### ISSUE TITLE
Applications can't be installed on the Tizen emulator

### ISSUE THREAD

**Issue by richardman1** [Samsung/cordova-plugin-toast#41]
After following the guidelines to make a media application demo, I can't install the application on the Tizen emulator, but it does work on the Tizen simulator.

The emulator doesn't give any description where it has failed.

**Comment by yongjuYoon** [comment]
Hi, @richardman1 

Please tell us your development environment.

For example, OS / Tizen studio version / emulator version and so on

Thank you.

**Comment by richardman1** [comment]
I am running on Windows 10 Enterprise with the following specs:
Processor: Intel(R) Xeon(R) CPU E5-1603 0 @ 2.80 GHz 2.80 GHz
Installed memory (RAM): 16.0 GB
System type: 64-bit Operation System, x64-based processor

This is a freshly installed desktop with the new Tizen Studio 1.1.1 version. 

The emulator is running on the tv-samsung 3.0 x86 platform. Has the HD1080 TV template with 1920x1080 resolution (32.0 inch). It has 4 processors and 102 MiB RAM. 

All I have done was install Tizen Studio, following your guidelines to make sample applications, and it simply cant install the application on the emulator.

**Comment by yongjuYoon** [comment]
When i tested sample TOAST media application, it operated normally with no errors.

So,, i'm not sure but maybe an error can be in a certificate.

So please make new certificate in your tizen studio.
http://developer.samsung.com/tv/develop/getting-started/setup-sdk/creating-certificates

Please tell us again if an error happens.

Thank you.

**Comment by richardman1** [comment]
Ok, 

I have created a new author and distributors certificate combined to my emulator in Tizen Studio.

I have updated the Grunt file profile name and prepared and built the application again. 

I have tried to install the app through Tizen Studio and through CLI. CLI gave me this output: 

![image](https://cloud.githubusercontent.com/assets/8642626/23949054/f063b290-0985-11e7-9035-214dfcffef5f.png)

Through Tizen studio Tizen project import from archive file i had to change the version from 2.3 to 3.0 and what I noticed is that in my ProjectExplorer behind the project is tv 3.0 instead of the usual tv-samsung-3.0:

![image](https://cloud.githubusercontent.com/assets/8642626/23949094/2bbec906-0986-11e7-87c9-d187d23d3e86.png)

Running it as usual by clicking the project and then run as samsung web application gave me this warning:

![image](https://cloud.githubusercontent.com/assets/8642626/23949117/516dcfbc-0986-11e7-9e2a-ca4d6d10ecab.png)

I hope this can help you

**Comment by yongjuYoon** [comment]
Did you check [this process](http://developer.samsung.com/tv/develop/getting-started/setup-sdk/creating-certificates#permit-to-install-applications)?
Please check this.

Nevertheless, if an error happens continuously, delete ".sign" folder in 'yourTOATproject'/platforms/sectv-tizen/www/.

And then please re-import the project.

If it is not solved above way, please send to us your entire TOAST project.

Thank you.

**Comment by richardman1** [comment]
Hello,

Thank you so much for your help. I forgot indeed to do the permit to install applications step. Now I can install it with Tizen Studio. Thank you again.
