### ISSUE TITLE
How to make TOAST project with Visual Studio

### ISSUE THREAD

**Issue by richardman1** [Samsung/cordova-plugin-toast#45]
Hi,

Not an issue but I cant get a TOAST application work with Visual Studio.

Any guides how to do this or another preferred IDE used by you?

**Comment by sukyunglee** [comment]
Hi,
first, sorry about your inconvenience.

TOAST project is based on CLI environment.
You can use  CLI tools such as git Bash.
Please refer to [Out Wiki page](https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-to-start).

For reference, 
if you build TOAST project to Tizen or WebOS application,
you can import it on Tizen or WebOS SDK.

**Comment by richardman1** [comment]
Okay thank you!
