### ISSUE TITLE
Fatal error: cordova.js, toast.js file are not exist.

### ISSUE THREAD

**Issue by dankunwizard** [Samsung/cordova-plugin-toast#46]
Running "grunt sectv-prepare" from Windows 7 returns below error message.

"Fatal error: cordova.js, toast.js file are not exist."

**Comment by sukyunglee** [comment]
Hi,
First, sorry for that.

Please refer to [Our Wiki Page](https://github.com/Samsung/cordova-plugin-toast/wiki/Create-Project).

In www/index.html chapter,
"Please note that cordova.js, toast.js have to be placed in bottom of <body> tag. (If placed to <head> tag, It causes timing issue.)"

Please check that.

**Comment by dankunwizard** [comment]
Below is last four lines of index.html file show the scripts are already at the bottom.

`        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="toast.js"></script>
    </body>
</html>
`

**Comment by sukyunglee** [comment]
Yes, sorry for my wrong reply.
Please check my opinion updated.

**Comment by dankunwizard** [comment]
grunt compile in cordova-js returns following:

Running "compile:amazon-fireos" (compile) task
Your version of amazon-fireos does not contain cordova-js-src. Update to a newer
 version of amazon-fireos.
Fatal error: Stopped process

**Comment by sukyunglee** [comment]
Maybe, your cordova-js repository is wrong.
(We also just use cordova-js repository.)

Please try again.

* "git clone" again this repository
* "npm install"
* add our task and platform (sectv-orsay, sectv-tizen and etc)
* finally "grunt"

Please refer to [Our Wiki Page](https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-to-start).

**Comment by dankunwizard** [comment]
Not sure what went wrong but using the batch file resolved the issue. It now compiles without any error. Thanks!

**Comment by DrNio13** [comment]
Hi, I am having similar issue and I am not sure if it is a config/installation issue or the browser emulator issue on OSX. Perhaps you can shine some light :)

<img width="852" alt="screen shot 2017-11-08 at 23 29 04" src="https://user-images.githubusercontent.com/11769448/32579215-6126e8d8-c4e0-11e7-9c47-0db66bd5d36b.png">
<img width="582" alt="screen shot 2017-11-08 at 23 26 36" src="https://user-images.githubusercontent.com/11769448/32579227-704896ea-c4e0-11e7-8f73-c20568891308.png">
<img width="1141" alt="screen shot 2017-11-08 at 23 54 10" src="https://user-images.githubusercontent.com/11769448/32579230-73cc1508-c4e0-11e7-8deb-408088d75d0c.png">

I followed the docs and i also used the compile command https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-to-start#compile 

Any ideas ? The project structure is correct ?

Thanks in advace!
Looking forward to use your library :)

**Comment by dyanakiev** [comment]
@DrNio13 have you found a fix?

**Comment by DrNio13** [comment]
@dyanakiev unfortunately no. i tried different solutions and installations at that time but nothing seemed to work.
