### ISSUE TITLE
My Http request just returns undefined on my tv while my emulator gives the result.

### ISSUE THREAD

**Issue by richardman1** [Samsung/cordova-plugin-toast#48]
Hi,

I am currently developing a TOAST application. I made it able to run it on an actual tv with some work-arounds(had to upload my certificates through the old Samsung TV IDE). So it runs good now, but the problem is that my tv does not execute the http request properly. This is possible with the simulator/emulator. Just not with the device. The TOAST application is built from scratch with the guide how you provided it on this GitHub page.

I have looked alot online on tizen forums, this toast page, samsung developers portal. I can't find a working solution. I even added some config stuff to the config file after building the toast application to tizen.

My request:

`httpGetAsync("http://randomuser.me/api");`

```
function httpGetAsync(url)
    {
    	$
    		.ajax({ url : url, type : "GET" })
    		.then( function( data, status, xhr ) {
    			console.log( data );
    			document.getElementById("error").innerHTML = String(data);
    		});
    }
```

My config file:

```
<?xml version="1.0" encoding="UTF-8"?>
<widget xmlns="http://www.w3.org/ns/widgets" xmlns:tizen="http://tizen.org/ns/widgets" id="http://yourdomain/NetTVClient" version="1.0.7" viewmodes="maximized">
    <tizen:application id="qitg5q58xo.NetTVClient" package="qitg5q58xo" required_version="2.3"/>
    <content src="index.html"/>
    <feature name="http://tizen.org/feature/screen.size.all"/>
    <icon src="img/logo.png"/>
    <name>NetTVClient</name>
    <tizen:privilege name="http://tizen.org/privilege/application.launch"/>
    <tizen:privilege name="http://developer.samsung.com/privilege/productinfo"/>
    <tizen:privilege name="http://developer.samsung.com/privilege/network.public"/>
    <tizen:privilege name="http://developer.samsung.com/privilege/drmplay"/>
    <tizen:privilege name="http://tizen.org/privilege/tv.inputdevice"/>
    <tizen:privilege name="http://tizen.org/privilege/tv.window"/>
    <tizen:privilege name="http://tizen.org/privilege/tv.channel"/>
    <tizen:privilege name="http://tizen.org/privilege/tv.audio"/>
    <tizen:privilege name="http://tizen.org/privilege/download"/>
    <tizen:privilege name="http://tizen.org/privilege/network.get"/>
    <access origin="*" subdomains="true"></access>
	<tizen:allow-navigation>https://randomuser.me/api</tizen:allow-navigation>
	<tizen:privilege name="http://tizen.org/privilege/internet"/>
    <tizen:profile name="tv"/>
</widget>
```

I am running on Windows 10 Professional with the following specs:
Processor: Intel(R) Xeon(R) CPU E5-1603 0 @ 2.80 GHz 2.80 GHz
Installed memory (RAM): 16.0 GB
System type: 64-bit Operation System, x64-based processor

This is a freshly installed desktop with the new Tizen Studio 1.1.1 version.

The TV we're talking about is a Samsung 6-Series FHD TV UE55J6240 that runs on Tizen 2.3 and the latest software version.

I hope you can help me.

With kind regards

**Comment by richardman1** [comment]
I found the solution myself after trying more.

I forgot to add the following two headers to the tizen platform in config.xml of my toast project:

```
<access origin="*" subdomains="true"></access>
<tizen:privilege name="http://tizen.org/privilege/internet"/>
```

**Comment by jandante** [comment]
Hi @richardman1.

I've got à simular issue with ajax requests but O do have the above lines in my config file at the tizen platform section.

Are there any other specifics you did to make it work?

My app works perfect on emulator but I can't find the correct setting to make it work on the tv device.
