### ISSUE TITLE
GlobalizationError not found null

### ISSUE THREAD

**Issue by vmazur** [Samsung/cordova-plugin-toast#5]
Hi samsung cordova developers, 

I followed instructions described here:
https://github.com/Samsung/cordova-plugin-toast
then
https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-and-Build

created WGT package, and after deploying on tizen emulator v. 2.4.0 build 20151013-1137

got this issue:

cordova.js (59) :module cordova/plugin/globalizatio.GlobalizationError not found
null
null
TypeError: 'undefined' is not a function (evaluating 'this.elPlugin.postMessageAndAwaitResponse(cmdObj)')
[HelloCordova.zip](https://github.com/Samsung/cordova-plugin-toast/files/173134/HelloCordova.zip)

could you please suggest if I missing something.

**Comment by prozanne** [comment]
Hi there. Could you explain more details? And HelloCordova.zip what you attached app looks like tizen appliction. Could you attach whole toast application what contains those directories: (ex.hooks, node_modules, platforms, plugins, www, .jshintrc, config.xml, Gruntfile.js, package.json)

we will check more and reply soon.

**Comment by vmazur** [comment]
Hi, 
thank you for quick response,
[HelloCordova.zip](https://github.com/Samsung/cordova-plugin-toast/files/173177/HelloCordova.zip)
<img width="1246" alt="screen shot 2016-03-14 at 10 33 19 pm" src="https://cloud.githubusercontent.com/assets/1488955/13766065/14f636b2-ea35-11e5-8019-a91ebfa7cb2f.png">
<img width="1161" alt="screen shot 2016-03-14 at 10 32 24 pm" src="https://cloud.githubusercontent.com/assets/1488955/13766064/14f5cc90-ea35-11e5-92f2-a6c4681f0b83.png">
[TestApp.zip](https://github.com/Samsung/cordova-plugin-toast/files/173179/TestApp.zip)

**Comment by prozanne** [comment]
Oh. It might.... 
Could you remove below code at index.html and try again?
At tizen application, csp rull is only applied at config.xml, but if there is in index.html It can conflict.

```xml
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">
```

**Comment by vmazur** [comment]
removed <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">

the issue related with "Content-Security-Policy" meta tag disappeared,  

however "cordova.js (59) :module cordova/plugin/globalizatio.GlobalizationError not found" still persists
<img width="1173" alt="screen shot 2016-03-14 at 10 57 13 pm" src="https://cloud.githubusercontent.com/assets/1488955/13766515/c841c29c-ea38-11e5-89c5-1c792527b194.png">

**Comment by prozanne** [comment]
Hi there again.
We found where that error occurs. And also fixed.
(Actually It is fundamentally bug of cordova-js. The project is official cordova project, so we can't modify directly and quickly. So... I fixed code temporarily our cordova-sectv-tizen.)

Anyway you don't need to see that error anymore.
After fixing code, It works well.
Could you try again with re-prepare and re-build?

**Comment by vmazur** [comment]
Confirmed, issue fixed, thanks.
