### ISSUE TITLE
Toast build for orsay not working

### ISSUE THREAD

**Issue by HosseinRashno** [Samsung/cordova-plugin-toast#53]
I create an application for smart tvs with TOAST project. During the development I test everything with tizen emulator and tizen studio and everything was fine.
After finishing development I tried to run the application on both orsay TV and orsay emulator and unfortunatly there was a lots of issue in that platform. I fixed some issues in design but I can't fix the main issue.
When I run the application, There is a line in console that say : deviceready has not fired after 5 seconds. And I can't use any of the TOAST api functionalities.
I create an empty project and do exactly what this page say: https://github.com/Samsung/cordova-plugin-toast#prepare-to-start 
But again I got the same error. Please help me.
Here is the log:

> cordova/platform: orsay bootstrap BEGIN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1365
adding proxy for NetworkStatus&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:887
adding proxy for Console&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:887
adding proxy for Device&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:887
adding proxy for Globalization&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:887
cordova/platform: orsay bootstrap END&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1460
adding proxy for toast.inputdevice&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
	return Window &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
adding proxy for toast.tvwindow&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
	return Window &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
adding proxy for toast.tvchannel&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
adding proxy for toast.tvaudiocontrol&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
adding proxy for toast.drminfo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
adding proxy for toast.application&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
adding proxy for toast.Media&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
Failed to load resource: fail to read a resource form decryptied file&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file:///home/smarttv/Apps/xThreeApp/cordova_plugins.js
deviceready has not fired after 5 seconds.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
Channel not fired: onNativeReady&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
Channel not fired: onCordovaReady&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
Channel not fired: onCordovaConnectionReady&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
Channel not fired: onCordovaInfoReady&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cordova.js:1880
![screenshot](https://user-images.githubusercontent.com/9047556/27001768-bbc220a8-4de6-11e7-99b3-b6588daf9f8e.jpg)

**Comment by HosseinRashno** [comment]
Ok I just find out two things:

- when I run the application on the emulator with `Debug As/Samsung Smart Tv Emulator` the `devicereaday` won't fired but if I close the app in the emulator and and open it again from the app page in emulator, the `deviceready` event will work perfect

- Even with the above trick, when I navigate to the second page, `deviceready` again won't fire! (Even I tried to navigate to the current page but second attamp will fail to fire the `deviceready` event)

I tried lots of method to navigating to the second page but all have the same result. (I use methods like `window.location.href = url;` and `window.location.replace(url);` and ...)

**Comment by darangkim** [comment]
Hello.
I'm sorry to late.

I checked the [TestRunner0607_Orsay](https://github.com/Samsung/cordova-plugin-toast/issues/17) again on 14's device(Orsay), there are no any problem.
If you share your application via e-mail, I can check it in detail.

Thank you.

**Comment by HosseinRashno** [comment]
Thank you so much for you response.
I send a copy of my Orsay project to your email.
Please note that 'deviceready' work in the first page but it doesn't work in the other pages.
Even in your ([TestRunner0607_Orsay.zip](https://github.com/Samsung/cordova-plugin-toast/files/302079/TestRunner0607_Orsay.zip)) project, when I reload the page or navigate to the page agian, 'deviceready' will not fired!
Thank you

**Comment by darangkim** [comment]
I'm sorry for the inconvenience.

There is a problem in cordova.js.
Because we were only testing for the One Screen App, we needed to handle exceptions for the multi Screen app.

The issue will be fixed on the git after further testing internally.
If you want to test before it, you can change the bootstrap function to the following source code in cordova.js.

    bootstrap: function() {
        console.log('cordova/platform: orsay bootstrap BEGIN');

        var modulemapper = require('cordova/modulemapper');
        var channel = require('cordova/channel');
        var SEF = require('cordova/plugin/SEF');
        var isWebapisLoaded = false;
        var isOnShowEventFire = false;

        modulemapper.clobbers('cordova/exec/proxy', 'cordova.commandProxy');

        var fireNativeReadyEvent = function() {
            if(isWebapisLoaded && isOnShowEventFire) {
                channel.onNativeReady.fire();
            }
        };

        for (var k in define.moduleMap) {
            if (/cordova.*\/proxy/.exec(k)) {
                require(k);
            }
            if (/cordova.*\/symbols/.exec(k)) {
                require(k);
            }
        }

        var head = document.getElementsByTagName('head')[0];
        var script = document.createElement('script');
        script.type = 'text/javascript';
        script.src = '$MANAGER_WIDGET/Common/webapi/1.0/webapis.js';
        script.onload = function() {
            isWebapisLoaded = true;
            fireNativeReadyEvent();
            require('cordova/plugin/ime-via-input');
        };
        head.appendChild(script);

        window.onPause = function () {
            channel.onPause.fire();
        };

        window.onResume = function () {
            channel.onResume.fire();
        };

        window.onHide = function() {
            localStorage.clear();
        };

        window.addEventListener('load', function () {
            var AppCommonPlugin = null;
            var NNaviPlugin = null;

            window.onShow = function () {
                localStorage.setItem('showEventFlag', 'true');
                settingInfo();
            };

            if(localStorage.getItem('showEventFlag') == 'true') {
                settingInfo();
            }

            if(window.curWidget && typeof window.curWidget.setPreference == 'function') {
                console.log('window.curWidget');
                window.curWidget.setPreference('ready', 'true');
            }
        });

        window.addEventListener('unload', function () {
            SEF.close();
        });

        window.addEventListener('keydown', function (e) {
            switch(e.keyCode) {
                case 88: // RETURN key
                    // default action disabled.
                    // Calling 'setPreference('return', 'true')' is needed explicitly to exit the application
                    e.preventDefault();
                    break;
                case 45: // EXIT key
                    // NOTHING to prevent.
                    break;
            }
        });

        function settingInfo() {
            try {
                AppCommonPlugin = SEF.get('AppCommon');
            }
            catch(e) {
                Error(e);
            }
            AppCommonPlugin.Execute('UnregisterAllKey');
            AppCommonPlugin.Execute('RegisterKey',29460); //up
            AppCommonPlugin.Execute('RegisterKey',29461); //down
            AppCommonPlugin.Execute('RegisterKey',4); //left
            AppCommonPlugin.Execute('RegisterKey',5); //right
            AppCommonPlugin.Execute('RegisterKey',29443); //enter
            AppCommonPlugin.Execute('RegisterKey',88); // return

            try {
                NNaviPlugin = SEF.get('NNavi');
            }
            catch(e) {
                Error(e);
            }

            NNaviPlugin.Execute('SetBannerState',2);
            isOnShowEventFire = true;
            fireNativeReadyEvent();
        }

        // End of bootstrap
        console.log('cordova/platform: orsay bootstrap END');
    }

**Comment by HosseinRashno** [comment]
Thank you for your time. I test your code but unfortunately I still have
the same problem. Here is the log:

cordova/platform: orsay bootstrap BEGIN
adding proxy for NetworkStatus
adding proxy for Console
adding proxy for Device
adding proxy for Globalization
cordova/platform: orsay bootstrap END
adding proxy for toast.inputdevice
return Window
adding proxy for toast.tvwindow
return Window
adding proxy for toast.tvchannel
adding proxy for toast.tvaudiocontrol
adding proxy for toast.drminfo
adding proxy for toast.application
adding proxy for toast.Media
[webapis.js] loading start
[webapis.js] Version : 1.2.14
Print: AllShare Web API  JS: 1.3.0.9
[webapis.js] loading finished
[webapis] onHide function added.
[webapis] onShow function added.
window.curWidget
deviceready has not fired after 5 seconds.
Channel not fired: onNativeReady
Channel not fired: onCordovaReady
Channel not fired: onCordovaConnectionReady
Channel not fired: onCordovaInfoReady

**Comment by HosseinRashno** [comment]
I'm so sorry for previous email, your code works great.
Thank you so much for your kindness. I wish you the best.
