### ISSUE TITLE
grunt sectv-build:sectv-tizen build failed please help me 

### ISSUE THREAD

**Issue by rajan995** [Samsung/cordova-plugin-toast#58]
Your environment has been set up for using Node.js 6.11.1 (x64) and npm.

C:\Users\rajan>cd ^BC:\Users\rajan\Desktop\tv\smarttv\smarttvapp
The filename, directory name, or volume label syntax is incorrect.

C:\Users\rajan>cd C:\Users\rajan\Desktop\tv\smarttv\smarttvapp

C:\Users\rajan\Desktop\tv\smarttv\smarttvapp>grunt sectv-prepare:sectv-tizen
Running "sectv-prepare:sectv-tizen" (sectv-prepare) task

Start preparing codes for Samsung Tizen Platform......
platforms\userconf.json
? What's the application's name? app
? Package Id (Valid RegExp: [0-9a-zA-Z]{10}) qw12erfgsd
? Application Version (Valid RegExp: /d./d./d) 1.0.0
? Icon path (default is 'img/logo.png') img/logo.png
? Application Description event
cp: no such file or directory: C:\Users\rajan\Desktop\tv\smarttv\cordova-js\pkg\cordova.sectv-tizen.js

Fatal error: cordova.js, toast.js file are not exist.

C:\Users\rajan\Desktop\tv\smarttv\smarttvapp>
successfully build on webos tv please help me to build on tizen

**Comment by prozanne** [comment]
Hi there,
In that case, It seems to be occured error with no toast.js and cordova.js.
Could you please check our guide [Prepare-to-start](https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-to-start#compile).

You need to compile for cordova-js(to make cordova.js) and cordova-plugin-toast(to make toast.js).
Please check again!

**Comment by rajan995** [comment]
thanks its working

In cordova-js/Gruntfile.js, please add compile tasks.

module.exports = function(grunt) {
grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    compile: {
        ...
        "sectv-orsay": {},
        "sectv-tizen": {},
        "tv-webos": {}
    },
In cordova-js/package.json, please add the platforms to cordova-platforms like below.

"cordova-platforms" : {
      ...
  "cordova-sectv-orsay"   : "../cordova-sectv-orsay",
  "cordova-sectv-tizen"   : "../cordova-sectv-tizen",
  "cordova-tv-webos"      : "../cordova-tv-webos"
}
Compile

In cordova-js, please grunt compile for packaging.

$ grunt compile:sectv-orsay compile:sectv-tizen compile:tv-webos
In cordova-plugin-toast, please grunt compile for packaging.

$ grunt compile:sectv-orsay compile:sectv-tizen compile:tv-webos

**Comment by rajan995** [comment]
thanks its working
