### ISSUE TITLE
TOAST with webOS TV

### ISSUE THREAD

**Issue by hiepnm** [Samsung/cordova-plugin-toast#6]
I found the news on Samsung forum like this:
http://www.samsungdforum.com/SamsungDForum/NewsView?newsID=93

But currently, It doesn't support for webOS TV. Is it really?

**Comment by prozanne** [comment]
Hi.

It's sorry that this sentence may have given confusion to you.
`In today's market, there are various Smart TV platforms including Samsung legacy platform, Samsung Tizen TV, WebOS TV, and others.`

This means, there are many various smart TV platforms in TODAY'S MARKET.
Currently TOAST has been supported Samsung Tizen TV, Samsung Legacy TV and browser right now. (Not yet WebOS TV)
We have a plan to expand supported platforms, in the future.

**Comment by Picato** [comment]
Thank prozanne.
