### ISSUE TITLE
App icon on grunt prepare

### ISSUE THREAD

**Issue by robinmg1** [Samsung/cordova-plugin-toast#7]
Hi developers,

I've been testing TOAST for some applications that will run on orsay, tizen 15 models and 16 models. 
I tried to generate the app icon using cordova tutorial (see the next url: https://cordova.apache.org/docs/en/5.0.0/config_ref/images.html) and did not work, so I need to do this manually on each config file.

Will be awesome if this task is added automatically on grunt prepare task.

Regards.

**Comment by prozanne** [comment]
I am really appreciate for your good suggest to make TOAST better.
We will try to consider and apply soon. Thanks.
