### ISSUE TITLE
Can't find variable: toast

### ISSUE THREAD

**Issue by aetchegoyen** [Samsung/cordova-plugin-toast#9]
Hi, when I try to debug my app on the OrsayTV emulator I get the following error: 

> Can't find variable: toast

I've followed all the steps in the wilki, and in the browser it just works fine, but in the emulator it just won't work.

What am I missing?

**Comment by sukyunglee** [comment]
Robin,
Hello.
This is Sue. First, thank you for your cercern.

I have checked this problem on OrsayTV Emulator,
(Samsung Smart SDK 5.1, https://www.samsungdforum.com/Devtools/SdkDownload)
it works well.
I want some information, your SDK version.

And
I wonder something for your app.
Do you insert <Script Tag> in index.html?
"<script type="text/javascript" src="toast.js"></script>"
Please check it.
This acrion is on Create Project Wiki Guide
(https://github.com/Samsung/cordova-plugin-toast/wiki/Create-Project).
I wonder if you miss this action.

Thanks.
Sue

**Comment by aetchegoyen** [comment]
Hi Sue! 
Thanks, after reinstalling everything on a new folder and creating the project again it worked. Maybe I missed a step.
I'll close the issue. 
Thanks!
